version: '3.8'

services:
  health-monitor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 22
        PORT: 3001
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Add your environment variables here or use .env file
      - ALLOWED_ORIGINS=http://localhost:3001,http://localhost:5173
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    env_file:
      - .env
    volumes:
      # Optional: Mount logs directory for persistence
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Development service with hot reload
  health-monitor-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
    profiles:
      - dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development 