version: '3.8'

services:
  backend-service:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend-network

  # Optional: Add Redis for session storage (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped
  #   networks:
  #     - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  # redis-data:

  # Optional: Add a simple test client
  test-client:
    image: curlimages/curl:latest
    depends_on:
      - backend-service
    command: >
      sh -c "
        echo 'Waiting for backend service to be ready...' &&
        until curl -f http://backend-service:3001/health; do
          sleep 2
        done &&
        echo 'Backend service is ready!' &&
        curl -s http://backend-service:3001/health | jq .
      "
    environment:
      - JQ_VERSION=1.6 